Added WASM , State and Spec files for Kusama Integration
DataHighway-DHX/DataHighway-Parachain pull request #39
Opened 2022-03-31 16:39 UTC by ayushmishra2005

1. Upgrade release to 3.6.0
2. Added WASM , State and Spec files for Kusama Integration

2022-03-31 21:51 UTC, ltfschoen requested changes
please rename this file, since i've named it datahighway-collator in the docs:
```
git mv ./res/kusama/compact.tar.gz ./res/kusama/datahighway-collator.tar.gz
```

i think this kusama file should be moved into the kusama subdirectory
```
git mv ./res/kusama.json ./res/kusama/kusama.json
```

i would prefer the following Rococo files to be moved into the rococo subdirectory:
```
git mv ./res/datahighway-collator.tar.gz ./res/rococo/datahighway-collator.tar.gz
git mv ./res/datahighway_parachain_runtime.compact.compressed.wasm ./res/rococo/datahighway_parachain_runtime.compact.compressed.wasm
git mv ./res/datahighway_parachain_runtime.compact.wasm ./res/rococo/datahighway_parachain_runtime.compact.wasm
git mv ./res/rococo-parachain-raw.json ./res/rococo/rococo-parachain-raw.json
git mv ./res/rococo-parachain-state ./res/rococo/rococo-parachain-state
git mv ./res/rococo-parachain-wasm ./res/rococo/rococo-parachain-wasm
git mv ./res/rococo.json ./res/rococo/rococo.json
```

2022-04-01 07:26 UTC, ltfschoen approved these changes, later dismissed

2022-04-01 07:56 UTC, cgroeschel requested changes
If we are not going to use docker builds, can you remove this file please: .github/workflows/docker.yml

2022-04-01 08:23 UTC, cgroeschel submitted a review, later dismissed

2022-04-01 08:57 UTC, cgroeschel approved these changes

2022-04-01 09:04 UTC, ltfschoen approved these changes

2022-04-01 09:40 UTC, merged