WIP: try to import example hardspoon account balances into genesis block
DataHighway-DHX/DataHighway-Parachain pull request #5
Opened 2022-02-03 08:28 UTC by ltfschoen

Unable to resolve this error:

previously i had a type for an account's public key defined as:
```
pub type AccountId = <Signature as Verify>::Signer;
```

and i'd get an account id of that type with:
```
<[u8; 32]>::from_hex(account_id).unwrap().unchecked_into()
```

but now that type for the public key has changed to:
```
pub type AccountId = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;
```

and when i try to get an account id of that type the same way
```
<[u8; 32]>::from_hex(account_id).unwrap().unchecked_into()
```

it gives error
```
error[E0277]: the trait bound `AccountId32: Wraps` is not satisfied
  --> node/src/fixtures.rs:34:39
34 |             <[u8; 32]>::from_hex(account_id).unwrap().unchecked_into(),
   |                                                ^^^^^^^^^^^^^^ the trait `Wraps` is not implemented for `AccountId32`
```

is that because with the new type definition for AccountId i now need to do something like the following?
```
use sp_core::{
    crypto::{UncheckedFrom, UncheckedInto, Wraps},
};
UncheckedFrom::unchecked_from(<[u8; 32]>::from_hex(account_id).unwrap().unchecked_into())
```

but if i do that i get error:
```
error[E0277]: the trait bound `H256: Wraps` is not satisfied
  --> node/src/fixtures.rs:34:69
   |
34 |             UncheckedFrom::unchecked_from(<[u8; 32]>::from_hex(account_id).unwrap().unchecked_into()),
   |                                                                              ^^^^^^^^^^^^^^ the trait `Wraps` is not implemented for `H256`
   |
   = note: required because of the requirements on the impl of `UncheckedFrom<[u8; 32]>` for `H256`
   = note: required because of the requirements on the impl of `UncheckedInto<H256>` for `[u8; 32]`
```

2022-02-21 12:31 UTC, ayushmishra2005 reviewed
@ltfschoen Can you perform local testing using https://docs.substrate.io/tutorials/v3/cumulus/start-relay/ and let me know if it is working fine

2022-02-23 14:33 UTC, ltfschoen commented
> https://docs.substrate.io/tutorials/v3/cumulus/start-relay/

it works fine with local testing using "rococo-local" by following these steps https://gist.github.com/ltfschoen/2e7b3f5508094b4179908507a8dffe58

2022-02-23 14:38 UTC, ltfschoen commented
> @ltfschoen Can you perform local testing using https://docs.substrate.io/tutorials/v3/cumulus/start-relay/ and let me know if it is working fine

> https://docs.substrate.io/tutorials/v3/cumulus/start-relay/

it works fine with local testing using "rococo-local" by following these steps https://gist.github.com/ltfschoen/2e7b3f5508094b4179908507a8dffe58

2022-03-09 15:07 UTC, ayushmishra2005 requested changes

2022-03-09 15:07 UTC, ayushmishra2005 commented on node/src/fixtures.rs
> +// use hex::{FromHex, FromHexError};
Can we remove all commented code from this file?

2022-03-09 15:54 UTC, ayushmishra2005 approved these changes

2022-03-09 16:06 UTC, merged